name: Deploy Quantic Match API Documentation

on:
  push:
    paths:
      - 'swagger.yaml'
      - '.github/workflows/swagger.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: NPM install
        run: npm install

      - name: Validate OpenAPI file
        run: npx speccy lint swagger.yaml

      - name: Deploy Swagger UI
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ECAZORLA_PAT }}
        run: |
          git clone https://github.com/swagger-api/swagger-ui.git
          cp swagger.yaml swagger-ui/dist/
          
          # Set Git configurations
          git config --global user.name "ecazorla"
          git config --global user.email "ecazorla@gmail.com"

          # Add commands to commit and push changes
          cd swagger-ui
          git add .
          git commit -m "Update Swagger UI with latest OpenAPI spec"
          # git push origin master