name: Deploy Quantic Match API Documentation

on:
  push:
    paths:
      - 'swagger.yaml'
      - '.github/workflows/swagger.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: NPM install
        run: npm install

      - name: Validate OpenAPI file
        run: npx speccy lint swagger.yaml

      - name: Deploy Swagger UI
        run: |
          git clone https://github.com/swagger-api/swagger-ui.git
          cp swagger.yaml swagger-ui/dist/
          cd swagger-ui
          git config user.name "Esteban Cazorla"
          git config user.email "ecazorla@gmail.com"
          git add .
          git commit -m "Update Swagger UI with latest OpenAPI spec"
          git push origin master