name: Deploy Quantic Match API Documentation

on:
  push:
    paths:
      - 'swagger.yaml'
      - '.github/workflows/swagger.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: quanticmatch/api-specs
          persist-credentials: false

      - name: NPM install
        run: npm install

      - name: Validate OpenAPI file
        run: npx speccy lint swagger.yaml
